# -*- coding: utf-8 -*-
"""ml phase 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y97FnYdWSTYR-qavQYA4jvxaleEL1D_y
"""

# connect to driver
from google.colab import drive
drive.mount('/content/drive')

# Speech Emotion Recognition - Clean Version

import pandas as pd
import matplotlib.pyplot as plt
import joblib

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, ConfusionMatrixDisplay

# Load dataset
female_df = pd.read_csv("/content/Female_features.csv")
male_df = pd.read_csv("/content/Male_features.csv")

df = pd.concat([female_df, male_df], ignore_index=True)

# Split features and target
X = df.drop("labels", axis=1)
y = df["labels"]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Scaling (optional but good for consistency)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Model training (BEST MODEL)
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Prediction
y_pred = model.predict(X_test)

# Evaluation
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred, average='weighted'))
print("Recall:", recall_score(y_test, y_pred, average='weighted'))
print("F1 Score:", f1_score(y_test, y_pred, average='weighted'))

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
ConfusionMatrixDisplay(cm).plot()
plt.show()

# Save model
joblib.dump(model, "emotion_model.pkl")
joblib.dump(scaler, "scaler.pkl")

# Prediction function
def predict_emotion(features):
    features = scaler.transform([features])
    return model.predict(features)[0]